<?php
/**
 * Created by PhpStorm.
 * User: stevewinter
 * Date: 09/07/2018
 * Time: 16:17
 */

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{

}